/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SchengRouteImport } from './routes/scheng'
import { Route as SchengIndexRouteImport } from './routes/scheng.index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SchengRoute = SchengRouteImport.update({
  id: '/scheng',
  path: '/scheng',
  getParentRoute: () => rootRouteImport,
} as any)
const SchengIndexRoute = SchengIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SchengRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/scheng': typeof SchengRouteWithChildren
  '/scheng/': typeof SchengIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/scheng': typeof SchengIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/scheng': typeof SchengRouteWithChildren
  '/scheng/': typeof SchengIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/scheng' | '/scheng/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/scheng'
  id: '__root__' | '/' | '/scheng' | '/scheng/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SchengRoute: typeof SchengRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scheng': {
      id: '/scheng'
      path: '/scheng'
      fullPath: '/scheng'
      preLoaderRoute: typeof SchengRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scheng/': {
      id: '/scheng/'
      path: '/'
      fullPath: '/scheng/'
      preLoaderRoute: typeof SchengIndexRouteImport
      parentRoute: typeof SchengRoute
    }
  }
}

interface SchengRouteChildren {
  SchengIndexRoute: typeof SchengIndexRoute
}

const SchengRouteChildren: SchengRouteChildren = {
  SchengIndexRoute: SchengIndexRoute,
}

const SchengRouteWithChildren =
  SchengRoute._addFileChildren(SchengRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SchengRoute: SchengRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
