/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as R3dschengRouteImport } from './routes/3dscheng'
import { Route as GuiafinRouteImport } from './routes/guiafin'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as SchengRouteImport } from './routes/scheng'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SchengIndexRouteImport } from './routes/scheng.index'
import { Route as SchengContactoRouteImport } from './routes/scheng.contacto'
import { Route as SchengGrupoRouteImport } from './routes/scheng.grupo'
import { Route as SchengValoresRouteImport } from './routes/scheng.valores'
import { Route as SchengEmpresasIndexRouteImport } from './routes/scheng.empresas.index'
import { Route as SchengEmpresasSlugRouteImport } from './routes/scheng.empresas.$slug'
import { Route as SchengProdutosSlugRouteImport } from './routes/scheng.produtos.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const R3dschengRoute = R3dschengRouteImport.update({
  id: '/3dscheng',
  path: '/3dscheng',
  getParentRoute: () => rootRouteImport,
} as any)
const GuiafinRoute = GuiafinRouteImport.update({
  id: '/guiafin',
  path: '/guiafin',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const SchengRoute = SchengRouteImport.update({
  id: '/scheng',
  path: '/scheng',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SchengIndexRoute = SchengIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SchengRoute,
} as any)
const SchengContactoRoute = SchengContactoRouteImport.update({
  id: '/contacto',
  path: '/contacto',
  getParentRoute: () => SchengRoute,
} as any)
const SchengGrupoRoute = SchengGrupoRouteImport.update({
  id: '/grupo',
  path: '/grupo',
  getParentRoute: () => SchengRoute,
} as any)
const SchengValoresRoute = SchengValoresRouteImport.update({
  id: '/valores',
  path: '/valores',
  getParentRoute: () => SchengRoute,
} as any)
const SchengEmpresasIndexRoute = SchengEmpresasIndexRouteImport.update({
  id: '/empresas/',
  path: '/empresas/',
  getParentRoute: () => SchengRoute,
} as any)
const SchengEmpresasSlugRoute = SchengEmpresasSlugRouteImport.update({
  id: '/empresas/$slug',
  path: '/empresas/$slug',
  getParentRoute: () => SchengRoute,
} as any)
const SchengProdutosSlugRoute = SchengProdutosSlugRouteImport.update({
  id: '/produtos/$slug',
  path: '/produtos/$slug',
  getParentRoute: () => SchengRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/3dscheng': typeof R3dschengRoute
  '/guiafin': typeof GuiafinRoute
  '/privacy': typeof PrivacyRoute
  '/scheng': typeof SchengRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/scheng/contacto': typeof SchengContactoRoute
  '/scheng/grupo': typeof SchengGrupoRoute
  '/scheng/valores': typeof SchengValoresRoute
  '/scheng/': typeof SchengIndexRoute
  '/scheng/empresas/$slug': typeof SchengEmpresasSlugRoute
  '/scheng/produtos/$slug': typeof SchengProdutosSlugRoute
  '/scheng/empresas/': typeof SchengEmpresasIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/3dscheng': typeof R3dschengRoute
  '/guiafin': typeof GuiafinRoute
  '/privacy': typeof PrivacyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/scheng/contacto': typeof SchengContactoRoute
  '/scheng/grupo': typeof SchengGrupoRoute
  '/scheng/valores': typeof SchengValoresRoute
  '/scheng': typeof SchengIndexRoute
  '/scheng/empresas/$slug': typeof SchengEmpresasSlugRoute
  '/scheng/produtos/$slug': typeof SchengProdutosSlugRoute
  '/scheng/empresas': typeof SchengEmpresasIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/3dscheng': typeof R3dschengRoute
  '/guiafin': typeof GuiafinRoute
  '/privacy': typeof PrivacyRoute
  '/scheng': typeof SchengRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/scheng/contacto': typeof SchengContactoRoute
  '/scheng/grupo': typeof SchengGrupoRoute
  '/scheng/valores': typeof SchengValoresRoute
  '/scheng/': typeof SchengIndexRoute
  '/scheng/empresas/$slug': typeof SchengEmpresasSlugRoute
  '/scheng/produtos/$slug': typeof SchengProdutosSlugRoute
  '/scheng/empresas/': typeof SchengEmpresasIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/3dscheng'
    | '/guiafin'
    | '/privacy'
    | '/scheng'
    | '/sitemap.xml'
    | '/terms'
    | '/scheng/contacto'
    | '/scheng/grupo'
    | '/scheng/valores'
    | '/scheng/'
    | '/scheng/empresas/$slug'
    | '/scheng/produtos/$slug'
    | '/scheng/empresas/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/3dscheng'
    | '/guiafin'
    | '/privacy'
    | '/sitemap.xml'
    | '/terms'
    | '/scheng/contacto'
    | '/scheng/grupo'
    | '/scheng/valores'
    | '/scheng'
    | '/scheng/empresas/$slug'
    | '/scheng/produtos/$slug'
    | '/scheng/empresas'
  id:
    | '__root__'
    | '/'
    | '/3dscheng'
    | '/guiafin'
    | '/privacy'
    | '/scheng'
    | '/sitemap.xml'
    | '/terms'
    | '/scheng/contacto'
    | '/scheng/grupo'
    | '/scheng/valores'
    | '/scheng/'
    | '/scheng/empresas/$slug'
    | '/scheng/produtos/$slug'
    | '/scheng/empresas/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  R3dschengRoute: typeof R3dschengRoute
  GuiafinRoute: typeof GuiafinRoute
  PrivacyRoute: typeof PrivacyRoute
  SchengRoute: typeof SchengRouteWithChildren
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermsRoute: typeof TermsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/3dscheng': {
      id: '/3dscheng'
      path: '/3dscheng'
      fullPath: '/3dscheng'
      preLoaderRoute: typeof R3dschengRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guiafin': {
      id: '/guiafin'
      path: '/guiafin'
      fullPath: '/guiafin'
      preLoaderRoute: typeof GuiafinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scheng': {
      id: '/scheng'
      path: '/scheng'
      fullPath: '/scheng'
      preLoaderRoute: typeof SchengRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scheng/': {
      id: '/scheng/'
      path: '/'
      fullPath: '/scheng/'
      preLoaderRoute: typeof SchengIndexRouteImport
      parentRoute: typeof SchengRoute
    }
    '/scheng/contacto': {
      id: '/scheng/contacto'
      path: '/contacto'
      fullPath: '/scheng/contacto'
      preLoaderRoute: typeof SchengContactoRouteImport
      parentRoute: typeof SchengRoute
    }
    '/scheng/grupo': {
      id: '/scheng/grupo'
      path: '/grupo'
      fullPath: '/scheng/grupo'
      preLoaderRoute: typeof SchengGrupoRouteImport
      parentRoute: typeof SchengRoute
    }
    '/scheng/valores': {
      id: '/scheng/valores'
      path: '/valores'
      fullPath: '/scheng/valores'
      preLoaderRoute: typeof SchengValoresRouteImport
      parentRoute: typeof SchengRoute
    }
    '/scheng/empresas/': {
      id: '/scheng/empresas/'
      path: '/empresas'
      fullPath: '/scheng/empresas/'
      preLoaderRoute: typeof SchengEmpresasIndexRouteImport
      parentRoute: typeof SchengRoute
    }
    '/scheng/empresas/$slug': {
      id: '/scheng/empresas/$slug'
      path: '/empresas/$slug'
      fullPath: '/scheng/empresas/$slug'
      preLoaderRoute: typeof SchengEmpresasSlugRouteImport
      parentRoute: typeof SchengRoute
    }
    '/scheng/produtos/$slug': {
      id: '/scheng/produtos/$slug'
      path: '/produtos/$slug'
      fullPath: '/scheng/produtos/$slug'
      preLoaderRoute: typeof SchengProdutosSlugRouteImport
      parentRoute: typeof SchengRoute
    }
  }
}

interface SchengRouteChildren {
  SchengContactoRoute: typeof SchengContactoRoute
  SchengGrupoRoute: typeof SchengGrupoRoute
  SchengValoresRoute: typeof SchengValoresRoute
  SchengIndexRoute: typeof SchengIndexRoute
  SchengEmpresasSlugRoute: typeof SchengEmpresasSlugRoute
  SchengProdutosSlugRoute: typeof SchengProdutosSlugRoute
  SchengEmpresasIndexRoute: typeof SchengEmpresasIndexRoute
}

const SchengRouteChildren: SchengRouteChildren = {
  SchengContactoRoute: SchengContactoRoute,
  SchengGrupoRoute: SchengGrupoRoute,
  SchengValoresRoute: SchengValoresRoute,
  SchengIndexRoute: SchengIndexRoute,
  SchengEmpresasSlugRoute: SchengEmpresasSlugRoute,
  SchengProdutosSlugRoute: SchengProdutosSlugRoute,
  SchengEmpresasIndexRoute: SchengEmpresasIndexRoute,
}

const SchengRouteWithChildren =
  SchengRoute._addFileChildren(SchengRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  R3dschengRoute: R3dschengRoute,
  GuiafinRoute: GuiafinRoute,
  PrivacyRoute: PrivacyRoute,
  SchengRoute: SchengRouteWithChildren,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermsRoute: TermsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
